
import { Task, TaskCategory, TaskStatus } from './types';

export const CATEGORY_COLORS: Record<string, string> = {
  [TaskCategory.VENUE]: "#8884d8",
  [TaskCategory.CATERING]: "#82ca9d",
  [TaskCategory.ATTIRE]: "#ffc658",
  [TaskCategory.PHOTOGRAPHY]: "#ff8042",
  [TaskCategory.MUSIC]: "#0088fe",
  [TaskCategory.DECOR]: "#00C49F",
  [TaskCategory.FLOWERS]: "#f472b6",
  [TaskCategory.STATIONERY]: "#94a3b8",
  [TaskCategory.BEAUTY]: "#fda4af",
  [TaskCategory.TRANSPORTATION]: "#7dd3fc",
  [TaskCategory.INVITATIONS]: "#FFBB28",
  [TaskCategory.GUEST_LIST]: "#FF8042",
  [TaskCategory.LEGAL]: "#a4de6c",
  [TaskCategory.HONEYMOON]: "#d0ed57",
  [TaskCategory.OTHER]: "#83a6ed",
};

export const STATUS_COLORS: Record<TaskStatus, string> = {
  [TaskStatus.COMPLETED]: "bg-emerald-100 text-emerald-800 border-emerald-200",
  [TaskStatus.IN_PROGRESS]: "bg-amber-100 text-amber-800 border-amber-200",
  [TaskStatus.DELAYED]: "bg-rose-100 text-rose-800 border-rose-200",
  [TaskStatus.NOT_STARTED]: "bg-slate-100 text-slate-800 border-slate-200",
};

export const SAMPLE_TASKS: Task[] = [
  {
    id: "1",
    name: "Book Wedding Venue",
    category: TaskCategory.VENUE,
    startDate: "2024-01-01",
    endDate: "2024-01-15",
    status: TaskStatus.COMPLETED,
    initialCost: 5000,
    actualCost: 5200,
    dependencies: [],
    notes: "Ensure capacity for 150 guests.",
    important: true,
  },
  {
    id: "2",
    name: "Finalize Guest List",
    category: TaskCategory.GUEST_LIST,
    startDate: "2024-01-05",
    endDate: "2024-01-20",
    status: TaskStatus.COMPLETED,
    initialCost: 0,
    actualCost: 0,
    dependencies: [],
    notes: "Collect addresses from parents.",
    important: true,
  },
  {
    id: "3",
    name: "Send Save the Dates",
    category: TaskCategory.INVITATIONS,
    startDate: "2024-01-21",
    endDate: "2024-02-01",
    status: TaskStatus.IN_PROGRESS,
    initialCost: 300,
    actualCost: 150,
    dependencies: ["1", "2"],
    notes: "Design approved, waiting on printing.",
    important: false,
  },
  {
    id: "4",
    name: "Book Caterer",
    category: TaskCategory.CATERING,
    startDate: "2024-02-01",
    endDate: "2024-02-28",
    status: TaskStatus.NOT_STARTED,
    initialCost: 4000,
    actualCost: 0,
    dependencies: ["1"],
    notes: "Tasting scheduled for Feb 10.",
    important: false,
  },
  {
    id: "5",
    name: "Buy Wedding Dress",
    category: TaskCategory.ATTIRE,
    startDate: "2024-01-15",
    endDate: "2024-03-01",
    status: TaskStatus.DELAYED,
    initialCost: 2000,
    actualCost: 0,
    dependencies: [],
    notes: "Need to reschedule fitting.",
    important: true,
  },
  {
    id: "6",
    name: "Book Photographer",
    category: TaskCategory.PHOTOGRAPHY,
    startDate: "2024-02-15",
    endDate: "2024-03-15",
    status: TaskStatus.NOT_STARTED,
    initialCost: 2500,
    actualCost: 0,
    dependencies: ["1"],
    notes: "Look for natural lighting style.",
    important: false,
  }
];
